public enum TokenType {
    INT, STRING, CHAR, BOOLEAN,
    IDENTIFIER, COMMA, SEMICOLON, COLON,

    LEFT_PAREN, RIGHT_PAREN,
    LEFT_CURLY, RIGHT_CURLY,
    LEFT_BRACKET, RIGHT_BRACKET,

    AND, OR, WHILE, FOR, IF, ELSE, ELSEIF,
    DEF, CLASS, RETURN, BREAK, CONTINUE,

    PLUS, MINUS, MULTIPLY, DIVIDE,

    EQUALS, EQUALS_EQUALS,
    LESS, LESS_EQUALS,
    GREATER, GREATER_EQUALS,
    NOT, NOT_EQUALS
}
